version: '2'
services:
  db:
    environment: 
        POSTGRES_USER: libuntl
        POSTGRES_PASS: libuntl
        POSTGRES_DBNAME: libuntl_db
    image: kartoza/postgis:9.6-2.4
    restart: always
    ports:
    - "5435:5432"
    volumes:
    - ./.source/db:/source
    - ./.postgresql_data/db:/var/lib/postgresql

  legacy:
    environment: 
        POSTGRES_USER: django
        POSTGRES_PASS: django
        POSTGRES_DBNAME: timordata_db
    image: kartoza/postgis:9.6-2.4
    restart: always
    ports:
    - "5436:5432"
    volumes:
    - ./.source/legacy:/source
    - /home/josh/github/timordata/timordata-postgres:/var/lib/postgresql
